name: Deploy via ftp
on: push
jobs:
  teste:
    - name: List files in the workspace directory
      run: ls /github/workspace
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: FTP Deploy Locaweb
        uses: locaweb/ftp-deploy@1.0.0

        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          localDir: "dist"
